// probe-deep500.mjs — push the deep GPU perturbation engines (rescaled + floatexp)
// PAST the current 2^-340 dispatch floor toward 2^-500+ and measure correctness vs
// the CPU perturbation oracle on a REAL deep boundary coordinate at HIGH maxIter.
//
// Why this exists: the existing validate-gpu "extreme depth" cases below 2^-340 are
// fast-escaping EXTERIOR patches at maxIter=1200 — they prove the fe ARITHMETIC holds
// at extreme exponent magnitude, but NOT that the df64-precision delta iteration still
// matches the oracle at the ~125k iterations a real 2^-500 boundary view needs. The
// companion's (correct) concern: error in the perturbation dz ACCUMULATES with
// iteration count; rebasing should bound it, but that must be MEASURED, not assumed.
//
// This tool reports, per depth: escaping-pixel count (esc — so we can see when a fixed
// coordinate runs out of true boundary structure), rs/fe mismatch %, max Δsn, inside
// mismatch, reference length, and the rs draw time. The TREND across depth is the
// signal: a FLAT mism% as maxIter grows ⇒ rebasing bounds the accumulation ⇒ extending
// the floor is safe. A coordinate string can be passed via RE/IM env (default: the
// generated deep boundary point from tools/gen-deep-coord.mjs, good to ~2^-520).
//
//   GPU=1 node tools/probe-deep500.mjs            (real GPU — the meaningful run)
//   GPU=1 BITS=271,340,400,500 node tools/probe-deep500.mjs
import { chromium } from '@playwright/test';
import { launchOpts } from './chromium-launch.mjs';
import { spawn } from 'node:child_process';

const PORT = process.env.PORT || 8147;
const server = spawn(process.execPath, ['tools/serve.mjs'], { env: { ...process.env, PORT }, stdio: 'ignore' });
const baseURL = `http://127.0.0.1:${PORT}`;
async function waitServer() {
  for (let i = 0; i < 100; i++) {
    try { const r = await fetch(baseURL + '/test/gpu/harness.html'); if (r.ok) return; } catch { /* retry */ }
    await new Promise((r) => setTimeout(r, 100));
  }
  throw new Error('server did not start');
}

// Default deep boundary coordinate generated by tools/gen-deep-coord.mjs — a GENUINE
// boundary point to ~2^-1010 (TARGET=1010 ITERCAP=280000; self-checked to straddle
// interior+exterior with escape counts spread near maxIter at 2^-990). Supersedes the
// earlier ~2^-520 coordinate now that the deep floor extends toward the precision wall.
// The shorter coordinates run out of true boundary structure below their bit length.
// Override via env (RE=… IM=…).
const RE = process.env.RE || '-1.36907801852007942475642195255842390507898755054806063192697077066791713514355984183138458726946811817965776911647030941610560712351758961905260413267881816077787468843042104473375047052708330910725794245355803318429014122085514645861629120057518448513757126947453394807972239491257672294147147329605986816418497391255';
const IM = process.env.IM || '-0.07181767684485165923310781763936598852851027483522667720017724564851969024779139147729278915346152412576593892660509339580393958961060780193289065314335145345663719866400233165980940228073309024466767811760569409475826736402394026213081093650425780165523756647946667328862361557720732262149429441085094730412969264871';
const autoIter = (bits) => Math.min(2_000_000, Math.round(400 + bits * 250));
const BITS = (process.env.BITS || '120,218,271,300,340,400,500').split(',').map(Number);
const W = Number(process.env.W || 32), H = Number(process.env.H || 32);

let fail = false;
try {
  await waitServer();
  const browser = await chromium.launch(launchOpts());
  const page = await browser.newPage();
  page.on('pageerror', (e) => { console.error('PAGE ERROR:', e.message); fail = true; });
  await page.goto(baseURL + '/test/gpu/harness.html');
  await page.waitForFunction(() => window.__ready === true, { timeout: 15000 });
  if (!(await page.evaluate(() => window.__gpu.init(256, 256))).supported) throw new Error('GPU not supported');
  console.log('renderer:', (await page.evaluate(() => window.__gpu.info())).renderer);
  console.log(`grid ${W}x${H}, deep boundary coordinate, maxIter = autoMaxIter(bits)\n`);
  console.log('depth     maxIter   ref  rsMs  esc   | rs mism   fe mism  | rs maxΔsn   rs insideMism');

  for (const bits of BITS) {
    const r = 1.5 * 2 ** -bits;
    const it = autoIter(bits);
    const base = { re: RE, im: IM, radius: r, maxIter: it, width: W, height: H, checkStep: 1, glitchTol: 0 };
    const t0 = Date.now();
    const dr = await page.evaluate((qq) => window.__gpu.comparePerturb(qq), { ...base, rs: true });
    const rsMs = Date.now() - t0;
    const df = await page.evaluate((qq) => window.__gpu.comparePerturb(qq), { ...base, fe: true });
    const esc = Math.max(1, dr.compared - dr.interiorCount);
    const rp = 100 * dr.mism / esc, fp = 100 * df.mism / esc;
    console.log(
      `2^-${String(bits).padEnd(4)} ${String(it).padStart(7)} ${String(dr.refLen).padStart(5)} ` +
      `${String(rsMs).padStart(5)} ${String(esc).padStart(5)}  | ${rp.toFixed(3).padStart(7)}% ${fp.toFixed(3).padStart(7)}% ` +
      `| ${dr.maxAbs.toExponential(2)}   ${dr.insideMismatch}`);
  }

  await browser.close();
  console.log('\n(rs/fe vs CPU oracle share the 53-bit reference; mism = the df64(46-bit)-delta gap.');
  console.log(' FLAT mism% as maxIter grows ⇒ rebasing bounds the per-iter accumulation ⇒ deep floor is safe.)');
} catch (e) {
  console.error('ERROR:', e.stack || e);
  fail = true;
} finally {
  server.kill();
}
process.exit(fail ? 1 : 0);
